global:
  scrape_interval: 10s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: /CADVISOR_HOST/metrics
    static_configs:
      - targets: [ 'CADVISOR_HOST:CADVISOR_PORT' ]

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:PROMETHEUS_PORT' ]
